### ISSUE TITLE
Backoff Retry Decider

### ISSUE THREAD

**Issue by bubba-h57** [stechstudio/backoff#1]
It would be nice to pass in a retry decider callback (similar to Guzzle) that allows backoff to determine whether it should continue retrying or not.

**Comment by rlanvin** [comment]
I would definitely be useful to have a callback before every retry, because at the moment it's not possible to interrupt it and so it's not usable in a command line script.

**Comment by jszobody** [comment]
Custom decider is now supported, see the bottom of the readme:

https://github.com/stechstudio/backoff#custom-retry-decider

You can now cause Backoff to retry as long as you want, or interrupt after any attempt. 

Thanks @bubba-h57 for the addition.
