### ISSUE TITLE
waitCap does not work

### ISSUE THREAD

**Issue by nachitox** [stechstudio/backoff#12]
If i'm not mistaken, `new Backoff(20, 'constant', 30000, true);` doesn't set the right wait time, because it uses:

```
        if (is_string($strategy) && array_key_exists($strategy, $this->strategies)) {
            return new $this->strategies[$strategy];
        }
```

which doesn't set Strategy's base value.

**Comment by jszobody** [comment]
Wait cap is applied _outside_ of the individual strategies.

https://github.com/stechstudio/backoff/blob/master/src/Backoff.php#L304-L323

The strategy is free to try and wait much longer than the cap, and the Backoff class still imposes whatever the max wait time is. Make sense?

**Comment by nachitox** [comment]
But `run()` calls `wait()` which calls `getWaitTime()` which is:

```
    public function getWaitTime($attempt)
    {
        $waitTime = call_user_func($this->getStrategy(), $attempt);

        return $this->jitter($this->cap($waitTime));
    }
```

`$waitTime` is always the base value because `AbstractStrategy`'s `$this->base` was not set by `return new $this->strategies[$strategy];`

```
    protected function cap($waitTime)
    {
        return is_int($this->getWaitCap())
            ? min($this->getWaitCap(), $waitTime)
            : $waitTime;
    }
```

Then, even it calls `getWaitCap()` which is the value I set, `$waitTime` might be lower.

**Comment by jszobody** [comment]
`min($this->getWaitCap(), $waitTime)` will return whichever is the lower value
