### ISSUE TITLE
FR: Define set of exception classes to be retried

### ISSUE THREAD

**Issue by arnegroskurth** [stechstudio/backoff#14]
Currently, this has to be implemented by the user via the `decider` setting. Could be simplified by e.g. providing a static `\STS\Backoff\Backoff::exceptionClassDecider(array $exceptionClasses): function` or similar helper-method.

**Comment by jszobody** [comment]
You want to provide an array of known exceptions, and only retry for those pre-defined exceptions? Any other exception would immediately fail with no retries?

I'm struggling to see this as a common use case, not sure this needs to be built-in to this library.

You can write your own decider class pretty easily...

```php
class RetryKnownExceptions {
    public function __construct(protected array $exceptions) {}

    public function __invoke($retry, $maxAttempts, $result = null, $exception = null) {
        // ...
    }
}


$backoff->setDecider(new RetryKnownExceptions($exceptionClasses));
```

Yeah? I think these kinds of unique cases would be better abstracted out into separate decider classes.

**Comment by SteenSchutt** [comment]
Given that I've done something similar, I think I can elaborate with an example.

I use this to retry HTTP requests, but I only want to retry on HTTP 503 and 504 (Basically temporarily unavailable services). Any other HTTP exception is considered a permanent failure. My error handler looks like this:

```php
$code = $exception->getCode();
if($code >= 400 && !in_array($code, [ 503, 504 ])) throw $exception;
```

In a perfect world, each of these conditions would be different exceptions, and I imagine OP is looking for a shortcut do something like that (e.g. retry on HttpServiceUnavailableException).

I am inclined to agree with Joseph, though. If you need that logic multiple times, you can just define and reference it yourself. I think the code is sufficiently simple and easy to not require a shorthand.

**Comment by jszobody** [comment]
I think I'm going to close this for now. It's could be useful, but I'm unlikely to have time to build it out anytime soon. 

If someone wanted to provide a PR, I'd be happy to review it. I would avoid using the static property approach, and instead provide a chainable method. Maybe something like...

```php
$backoff
    ->retryWhen([HttpServiceUnavailableException::class])
```

The default decider function would then only retry when the caught exception matches one of these, and would immediately fail up otherwise.
