### ISSUE TITLE
Backoff Error Callback

### ISSUE THREAD

**Issue by bubba-h57** [stechstudio/backoff#2]
Would be nice to have a callback on an error, to do things like logging.

**Comment by Lewiscowles1986** [comment]
@bubba-h57 PR?

**Comment by bubba-h57** [comment]
Yes. PR indeed!

**Comment by Lewiscowles1986** [comment]
Just looked over this 

https://github.com/stechstudio/backoff/blob/master/src/Backoff.php#L268:L273

Seems that you could simply send in a new decider implementation, and that this would be most flexible in that case, without this library taking on more responsibilities. Could be moved to `documentation` tag?

**Comment by bubba-h57** [comment]
https://github.com/stechstudio/backoff#custom-retry-decider allows you to do that, but I think I want an actual callback.

**Comment by bubba-h57** [comment]
If you look at https://github.com/stechstudio/backoff/blob/master/src/Backoff.php#L223-L249 you will see that you have two real options.

*First*
Just catch any exceptions in the `$callback` that you are running, and handle logging there. Something like this:

```PHP
function doSomeWorkThatMightFail() {
    try {
        somethingElseThatMightFail();
    } catch( Exception $e) {
        // log stuff, etc.
        throw $e;
   }
}
$result = backoff(function() {
    return doSomeWorkThatMightFail();
});
```

However, if you are looking for more information, say you want to track the current attempt, max attempts, etc. Then you would implement your own decider and handle it there.

```php
$backoff->setDecider(function($attempt, $maxAttempts, $result, $exception = null) {
     // log stuff, etc. 
    if ($retry >= $maxAttempts || is_null($exception)) {
               // log stuff, etc. 
                return false;
            }
             // log stuff, etc. 
            return true;
})
```

**Comment by bubba-h57** [comment]
@jszobody comments, thoughts?

**Comment by Lewiscowles1986** [comment]
I was going to mention that what you described RE getting attempt, maxAttempts is what is in the decider at the moment. If it walks like a duck, quacks like a duck, was the rationale for that (it is a callback really). 

I feel like the `run` function is a little long as-is (lots going on).

* [L226-L227](https://github.com/stechstudio/backoff/blob/master/src/Backoff.php#L226-L227) is repeated in [L234-L235](https://github.com/stechstudio/backoff/blob/master/src/Backoff.php#L234-L235) for example. Why not hoist to 232 just inside the while loop?
* Also why assign `$this->decider` to `$decider`?
* [L244-L246](https://github.com/stechstudio/backoff/blob/master/src/Backoff.php#L244-L246) could this be left to the decider (which seems to bubble the throw anyway?)

**Comment by jszobody** [comment]
Thoughts on 51eed40b8f3346c783a70f76f1707bdcd2d0b44d? See test for example usage.

**Comment by jszobody** [comment]
Release 1.0.0 contains the changes from PR #5 and also the new error handler
