### ISSUE TITLE
travis or alternative CI?

### ISSUE THREAD

**Issue by Lewiscowles1986** [stechstudio/backoff#6]
At some point if you're agreeable I can PR travis with badge so that all PR's are tested?

**Comment by jszobody** [comment]
Sure, I'd welcome that.

**Comment by jszobody** [comment]
Hmm... actually Scrutinizer is already setup, the build badge is displaying already. It should be checking PRs as well from what I can tell?

**Comment by Lewiscowles1986** [comment]
I may have just learned something about scrutinizer. I've never used it. Apologies
